// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJwaGiotlQu3zg9-I_XFMO5PhWiJP3D60',
    appId: '1:783610146926:web:af486a79989277653b767f',
    messagingSenderId: '783610146926',
    projectId: 'disposetest-26d48',
    authDomain: 'disposetest-26d48.firebaseapp.com',
    storageBucket: 'disposetest-26d48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lZbQwtMDYk8vbK3NxAYZ28MoU7Tpy60',
    appId: '1:783610146926:android:bafa81d3024a2d2e3b767f',
    messagingSenderId: '783610146926',
    projectId: 'disposetest-26d48',
    storageBucket: 'disposetest-26d48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKfLishBYFPeySh044wnhV3qkDJplJro',
    appId: '1:783610146926:ios:4e07580563b73c143b767f',
    messagingSenderId: '783610146926',
    projectId: 'disposetest-26d48',
    storageBucket: 'disposetest-26d48.appspot.com',
    iosClientId: '783610146926-agfsonpaiir99giss85c1d0v41kl8tfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disposeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzKfLishBYFPeySh044wnhV3qkDJplJro',
    appId: '1:783610146926:ios:4e07580563b73c143b767f',
    messagingSenderId: '783610146926',
    projectId: 'disposetest-26d48',
    storageBucket: 'disposetest-26d48.appspot.com',
    iosClientId: '783610146926-agfsonpaiir99giss85c1d0v41kl8tfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disposeTest',
  );
}
